### ISSUE TITLE
请问作者还在更新吗

### ISSUE THREAD

**Issue by OIer1048576** [ilhikki/hott-book-zh#1]

**Comment by ilhikki** [comment]
在更新，不过较忙

**Comment by alex-ca1123** [comment]
别担心, 他不更新我更新, 我自己的初稿已经要搞完Part I, 搞到同伦-n类型了. 但是我的格式和这个仓库不一样, 我把格式调整一下. 然后我们合并了算了. 我现在是迫切的要搞到实数, 因为我特别需要那个Disequality Implies Apartness(or not).
